# ===================================
# Relation Behavior Config
# ===================================

ticket_group:
    label: waka.support::ticket.ticket_group
    manage:
        form: $/waka/support/models/ticketgroup/fields_for_ticket.yaml
        list: $/waka/support/models/ticketgroup/columns_for_ticket.yaml
        filter: config_filters_for_ticket_group.yaml
    view:
        form: $/waka/support/models/ticketgroup/fields_for_ticket_read.yaml
        recordUrl: waka/support/ticketgroup/update/:id
        toolbarButtons: create|link|unlink
        defaultSort:
            column: name
            direction: asc

