ticket_w:
    type: state_machine
    metadata: 
        name: waka.support::ticket_w.name 
        com: waka.support::ticket_w.com 
        rulesSets:
            default:
                fields:  
                messages: waka.support::ticket_w_errors
            none:
                fields:  
                messages: waka.support::ticket_w_errors
            factu:
                fields:  
                    price: required              
                messages: waka.support::ticket_w_errors
    marking_store:
        type: single_state
        property: state
    supports:
        - \Waka\Support\Models\Ticket
    places:
        draft:
            metadata:
                label: waka.support::ticket_w.places.draft 
                icon: wicon-pencil2
                hidden_fields: [awake_at]
        wait_support:
            metadata:
                label: waka.support::ticket_w.places.wait_support 
                icon: icon-clock-o
                hidden_fields: [awake_at]
        wait_managment:
            metadata:
                label: waka.support::ticket_w.places.wait_managment 
                icon: icon-clock-o
                hidden_fields: [awake_at]
        running:
            metadata:
                label: waka.support::ticket_w.places.running 
                icon: icon-cogs
                hidden_fields: [awake_at]
        validated:
            metadata:
                label: waka.support::ticket_w.places.validated 
                icon: icon-check
                hidden_fields: [awake_at]
        sleep:
            metadata:
                label: waka.support::ticket_w.places.sleep 
                icon: icon-bed
        archived:
            metadata:
                label: waka.support::ticket_w.places.archived 
                icon: icon-cubes
                must_trans: true
                hidden_fields: [awake_at]
        abdn:
            metadata:
                label: waka.support::ticket_w.places.abdn 
                icon: icon-trash-o
                hidden_fields: [awake_at]
    initial_places: draft  # or set to an array if multiple initial places
    transitions:
        draft_to_wait_support:
            metadata: 
                label: waka.support::ticket_w.trans.draft_to_wait_support 
                rulesSet: none
                redirect: "redirect:1"
                type: success
                fncs:
                    sendNotification:
                        type: prod
                        args:
                            code: waka.support::new_ticket
                            mode: support
            from: draft
            to: wait_support
        draft_to_wait_managment:
            metadata: 
                label: waka.support::ticket_w.trans.draft_to_wait_managment 
                redirect: "redirect:1"
                type: success
                fncs:
                    sendNotification:
                        type: prod
                        args:
                            code: waka.support::new_ticket
                            mode: client
                    isSupport:
                        type: gard
            from: draft
            to: wait_managment
        draft_to_sleep:
            metadata: 
                label: waka.support::ticket_w.trans.draft_to_sleep 
                type: info
                fncs:
                    askSleep:
                        type: prod
            from: draft
            to: sleep
        draft_to_abdn:
            metadata: 
                label: waka.support::ticket_w.trans.draft_to_abdn 
                redirect: "redirect:1"
                type: danger
                fncs:
                    isCreatorAsking:
                        type: gard
            from: draft
            to: abdn
        draft_to_validated:
            metadata: 
                label: waka.support::ticket_w.trans.draft_to_validated 
                redirect: "close:1"
                type: success
                fncs:
                    isCreatorAsking:
                        type: gard
            from: draft
            to: validated
        wait_support_to_wait_managment:
            metadata: 
                label: waka.support::ticket_w.trans.wait_support_to_wait_managment 
                redirect: "redirect:1"
                fncs:
                    sendNotification:
                        type: prod
                        args:
                            code: waka.support::new_ticket
                            mode: client
                    isSupport:
                        type: gard
            from: wait_support
            to: wait_managment
        wait_support_to_sleep:
            metadata: 
                label: waka.support::ticket_w.trans.wait_support_to_sleep 
                fncs:
                    askSleep:
                        type: prod
                    isSupport:
                        type: gard
            from: wait_support
            to: sleep
        wait_support_to_abdn:
            metadata: 
                label: waka.support::ticket_w.trans.wait_support_to_abdn 
                redirect: "redirect:1"
                type: danger
                fncs:
                    isCreatorAsking:
                        type: gard
            from: wait_support
            to: abdn
        wait_support_to_running:
            metadata: 
                label: waka.support::ticket_w.trans.wait_support_to_running 
                redirect: "redirect:1"
                fncs:
                    isSupport:
                        type: gard
            from: wait_support
            to: running
        running_to_wait_managment:
            metadata: 
                label: waka.support::ticket_w.trans.running_to_wait_managment 
                redirect: "close:1"
                fncs:
                    isSupport:
                        type: gard
            from: running
            to: wait_managment
        wait_managment_to_wait_support:
            metadata: 
                label: waka.support::ticket_w.trans.wait_managment_to_wait_support 
                redirect: "close:1"
                fncs:
                    sendNotification:
                        type: prod
                        args:
                            code: waka.support::new_ticket
                            mode: support
            from: wait_managment
            to: wait_support
        wait_managment_to_validated:
            metadata: 
                label: waka.support::ticket_w.trans.wait_managment_to_validated 
                redirect: "close:1"
                fncs:
                    sendNotification:
                        type: prod
                        args:
                            code: waka.support::new_ticket
                            mode: support
                    isClient:
                        type: gard
            from: wait_managment
            to: validated
        wait_managment_to_sleep:
            metadata: 
                label: waka.support::ticket_w.trans.wait_managment_to_sleep 
                fncs:
                    askSleep:
                        type: prod
            from: wait_managment
            to: sleep
        wait_managment_to_abdn:
            metadata: 
                label: waka.support::ticket_w.trans.wait_managment_to_abdn 
                redirect: "redirect:1"
                type: danger
                fncs:
                    isCreatorAsking:
                        type: gard
            from: wait_managment
            to: abdn
        sleep_to_wait_support:
            metadata: 
                label: waka.support::ticket_w.trans.sleep_to_wait_support 
                redirect: "redirect:1"
            from: sleep
            to: wait_support
        sleep_to_wait_managment:
            metadata: 
                label: waka.support::ticket_w.trans.sleep_to_wait_managment 
                redirect: "redirect:1"
                fncs:
                    isSupport:
                        type: gard
            from: sleep
            to: wait_managment
        sleep_to_validated:
            metadata: 
                label: waka.support::ticket_w.trans.sleep_to_validated 
                redirect: "redirect:1"
            from: sleep
            to: validated
        validated_to_archived:
            metadata: 
                label: waka.support::ticket_w.trans.validated_to_archived 
                redirect: "close:1"
            from: validated
            to: archived
        to_archived_factu:
            metadata: 
                label: waka.support::ticket_w.trans.to_archived_factu 
                hidden: true
                fncs:
                    createChildTicket:
                        type: trait_onEnter
            from: 
                - wait_managment
                - wait_support
                - sleep
                - draft
            to: archived
